### PR TITLE
Add in github token variable

### PR DESCRIPTION
**Pull request by ghostdevv**
So those of us on private repos can use this

### CODE REVIEW

**Comment by ghostdevv** [comment]
Unfortunately haven't been able to get this to work on tauri side yet since tauri would be unauthenticated against github

**Comment by RyKilleen** [comment]
Haven't had to add Tauri build actions to a private repo, but let us know if we can help at all.

I'll give this a trial run tonight or tomorrow!

**Comment by RyKilleen** [comment]
Ah okay, I see the challenge you're facing now!

Given what the Cloudflare worker is already doing, I think we could add a simple proxy to the release files. That would technically expose them publicly, however. Not sure if that's acceptable in your case.

**Comment by ghostdevv** [comment]
It might be nice to add the proxy anyway and that way we can even add authentication logic to the worker? If you want your worker private and only accessible by your tauri app which will have the key

**Comment by RyKilleen** [comment]
Let's do this, I'll merge this since it's definitely complete enough.

Would you mind opening an issue with what you found so far? Happy to add the file proxy, but I'm not sure worker auth is possible without changes in Tauri.

Feel free to tag me in those discussions on GitHub/discord as needed!

**Pull request merged**
